#!/bin/bash
#AUTOR JORGE DIAS jorgediasdsg@gmail.com https://github.com/jorgediasdsg/email https://gitlab1.cbm.sc.gov.br/redes/email
e(){ echo $1; }; p(){ clear; seq 7 8 180 | paste -sd \X; e ""; e "	INSTALAÇÃO DE CLIENTE GMAIL PARA TERMINAL"; e ""; e "	$1"; e ""; if [ -n "$2" ]; then e "	$2"; e ""; fi; if [ -n "$3" ]; then e "		$3"; e ""; fi; if [ -n "$4" ]; then e "	$4"; e ""; fi; seq 9 7 160 | paste -sd \X; e ""; e ""; }
cmil(){ e "" > f; e "Olá," >> f; e "" >> f; e "Se você está lendo essa mensagem é porque deu certo a coisa..." >> f; e "" >> f; e "Agora que já tem configurado cliente de e-mail em seu computador você pode automatizar seus scripts." >> f; e "" >> f; e "Use o comando abaixo para isso..." >> f; e "" >> f; e "mutt -s 'Assunto do E-mail' destino@email.com < corpodoemail.txt -a anexo.zip" >> f; e "" >> f; e "Até mais." >> f; e ""; e "https://github.com/jorgediasdsg/email" >> f; } #CRIANDO E-MAIL DE CONFIRMAÇÃO.
idata(){ p "DIGITE SEU GMAIL"; read EMAILGMAIL; p "DIGITE SEU NOME "; read NOME; p "COPIE O LINK ABAIXO E COLE NO NAVEGADOR - FAÇA A SENHA PARA O APP" "https://myaccount.google.com/apppasswords" "CASO NÃO TENHA AUTENTICAÇÃO 2 ETAPAS E ESTIVER CONFIANDO EM APLICATIVOS INSEGUROS PODE DIGITAR SUA SENHA NORMAL" "COLE AQUI COM CTRL+SHIFT+V E APERTE ENTER"; read SENHAGMAIL; p "CONFIRA AS INFORMAÇÕES E APERTE ENTER PARA CONTINUAR OU CTRL+C PARA CANCELAR" "EMAIL: $EMAILGMAIL NOME: $NOME SENHA DO APP: $SENHAGMAIL"; read APERTEENTER; } #INTERAÇÃO COM USUARIO CAPTURANDO EMAIL E SENHA.
iapps(){ sudo apt-get install sendmail -y; sudo apt-get install mutt -y; } #INSTALAÇÃO DOS APPS
scfg(){ p "CRIANDO .CONF"; [ ! -d "$HOME/.muttrc" ] || p "JÁ EXISTE UMA INSTALAÇÃO" "RENOMEANDO .OLD AGUARDE..."; mv $HOME/.muttrc $HOME/.muttrc-old; e "set ssl_starttls='yes' " >> $HOME/.muttrc; e "set ssl_force_tls='yes' " >> $HOME/.muttrc; e "set imap_user='$EMAILGMAIL' " >> $HOME/.muttrc; e "set imap_pass='*$SENHAGMAIL' " >> $HOME/.muttrc; e "set from='$EMAILGMAIL' " >> $HOME/.muttrc; e "set realname='$NOME' " >> $HOME/.muttrc; e "set folder='imaps://imap.gmail.com/' " >> $HOME/.muttrc; e "set spoolfile='imaps://imap.gmail.com/INBOX' " >> $HOME/.muttrc; e "set postponed='imaps://imap.gmail.com/[Gmail]/Drafts' " >> $HOME/.muttrc; e "set smtp_url='smtps://$EMAILGMAIL:$SENHAGMAIL@smtp.gmail.com:465/' " >> $HOME/.muttrc; e "set move='no' " >> $HOME/.muttrc; e "set imap_keepalive='900'" >> $HOME/.muttrc; }
smail(){ p "ENVIANDO EMAIL CONFIRMAÇÃO"; mutt -s "Confirmação de email "$EMAILGMAIL $EMAILGMAIL < f -a mail.sh; rm -rf f; p "INSTALAÇÃO ENCERRADA - CONFIRA SEU E-MAIL - ACESSE" "https://github.com/jorgediasdsg/email" "https://gitlab1.cbm.sc.gov.br/redes/email"; }
cmil; idata; iapps; scfg; smail
